// Fixture data for the read-only/session-scoped demo shop at slug 'demo-shop'.
// Never write to Supabase from anything that consumes this module.

export const DEMO_SLUG = 'demo-shop'

export function isDemoShop(slug) {
  return slug === DEMO_SLUG
}

const demoNow = new Date()

function ago(days, hours = 0) {
  return new Date(demoNow.getTime() - (days * 24 + hours) * 60 * 60 * 1000).toISOString()
}

export const demoShop = {
  id: 'demo-shop-uuid-0000-0000-000000000000',
  name: 'Ridge Auto Service',
  slug: DEMO_SLUG,
  plan: 'growth',
  contact_email: 'ridge@example.com',
  contact_phone: '(434) 555-0142',
  timezone: 'America/New_York',
  signup_status: 'active',
  address: '412 Preston Ave, Charlottesville, VA 22903',
  created_at: ago(138),
}

export const demoMembers = [
  { user_id: 'demo-owner-0000', email: 'owner@ridgeauto.example.com', role: 'owner' },
  { user_id: 'demo-tech-0001', email: 'mike.tech@ridgeauto.example.com', role: 'member' },
  { user_id: 'demo-tech-0002', email: 'sara.tech@ridgeauto.example.com', role: 'member' },
]

const DISCLAIMER =
  "This brief is generated from customer-reported symptoms and is not a diagnosis. A technician should confirm before repair."

// A tiny, always-playable silent WAV — avoids console errors from a dead network URL
// while still exercising the real <audio> element in RawEvidence.
const SILENT_AUDIO_DATA_URI =
  'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA='

function photo(text) {
  return `https://placehold.co/800x600/1a1a1a/ffffff?text=${encodeURIComponent(text)}`
}

export const demoIntakes = [
  // Today
  {
    id: 'demo-01',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Brakes',
      urgency: 'immediate',
      urgencyLabel: 'See us today',
      probableCauses: [
        { cause: 'Worn front brake pads (metal wear indicator contact)', confidence: 82 },
        { cause: 'Glazed rotor surface', confidence: 41 },
      ],
      componentsToInspect: ['Front brake pads', 'Rotor surface', 'Caliper slide pins'],
      estimateRange: [180, 340],
      symptomLanguage: [
        "It sounds like a hairdryer when I brake going downhill on 250, but only if the car's been sitting a while.",
        'Gets quieter after a few stops.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: true, video: false, text: true },
    },
    urgency: 'immediate',
    category: 'Brakes',
    customer_name: 'Danielle R.',
    vehicle: { year: 2018, make: 'Honda', model: 'Civic' },
    created_at: ago(0, 3),
    updated_at: ago(0, 3),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },
  {
    id: 'demo-02',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Steering & Suspension',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'Wheel/tire imbalance', confidence: 58 },
        { cause: 'Warped brake rotor causing pulsation felt through steering', confidence: 33 },
      ],
      componentsToInspect: ['Wheel balance', 'Tire condition', 'Front rotors'],
      estimateRange: [60, 220],
      symptomLanguage: [
        'Steering wheel shakes a little around 55-60 mph, smooths out above that.',
        "Been going on for about two weeks.",
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Steering & Suspension',
    customer_name: 'Marcus T.',
    vehicle: { year: 2020, make: 'Toyota', model: 'RAV4' },
    created_at: ago(0, 5),
    updated_at: ago(0, 5),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },
  {
    id: 'demo-03',
    shop_id: demoShop.id,
    status: 'in_progress',
    brief: null,
    urgency: null,
    category: null,
    customer_name: 'Priya K.',
    vehicle: { year: 2019, make: 'Ford', model: 'Escape' },
    created_at: ago(0, 1),
    updated_at: ago(0, 1),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },

  // Yesterday
  {
    id: 'demo-04',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Off-topic',
      urgency: 'immediate',
      urgencyLabel: 'See us today',
      probableCauses: [
        { cause: 'Unable to determine — submission did not describe a mechanical issue', confidence: 0 },
      ],
      componentsToInspect: [],
      estimateRange: [0, 0],
      symptomLanguage: [
        '(No mechanical symptom described — customer uploaded photos of interior upholstery wear.)',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: false, photo: true, video: false, text: false },
    },
    urgency: 'immediate',
    category: 'Off-topic',
    customer_name: null,
    vehicle: { year: 2015, make: 'Ford', model: 'F-150' },
    created_at: ago(1, 4),
    updated_at: ago(1, 2),
    flagged: true,
    flagged_reason: 'Off-topic',
    flagged_at: ago(1, 2),
    archived_at: null,
    rating: null,
  },
  {
    id: 'demo-05',
    shop_id: demoShop.id,
    status: 'in_progress',
    brief: null,
    urgency: null,
    category: null,
    customer_name: 'Wei L.',
    vehicle: { year: 2012, make: 'Toyota', model: 'Camry' },
    created_at: ago(1, 6),
    updated_at: ago(1, 6),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },
  {
    id: 'demo-06',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Drivetrain',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'Worn CV joint on right front axle', confidence: 64 },
        { cause: 'Low-grade wheel bearing wear under load', confidence: 28 },
      ],
      componentsToInspect: ['Right front CV joint', 'Front wheel bearings', 'Transfer case fluid level'],
      estimateRange: [220, 480],
      symptomLanguage: [
        'Grinding noise only when I turn right, especially in parking lots.',
        "Doesn't happen going straight or turning left.",
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Drivetrain',
    customer_name: 'Tom H.',
    vehicle: { year: 2016, make: 'Subaru', model: 'Outback' },
    created_at: ago(1, 8),
    updated_at: ago(1, 8),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },
  {
    id: 'demo-07',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Electrical',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'Parasitic draw from aftermarket amplifier wiring', confidence: 47 },
        { cause: 'Aging battery losing capacity', confidence: 55 },
      ],
      componentsToInspect: ['Battery load test', 'Aftermarket electronics wiring', 'Alternator output'],
      estimateRange: [40, 260],
      symptomLanguage: [
        "Car is dead most mornings if I don't drive it for 2 days.",
        'Battery is original, I think.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: false, photo: false, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Electrical',
    customer_name: 'Grace O.',
    vehicle: { year: 2017, make: 'Nissan', model: 'Altima' },
    created_at: ago(1, 10),
    updated_at: ago(1, 10),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },

  // 3 days ago
  {
    id: 'demo-08',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Steering & Suspension',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'Worn tie rod ends', confidence: 78 },
        { cause: 'Loose track bar bushing', confidence: 35 },
      ],
      componentsToInspect: ['Tie rod ends', 'Track bar bushings', 'Steering stabilizer'],
      estimateRange: [180, 420],
      symptomLanguage: [
        'Wanders side to side over 40, have to keep correcting.',
        'Steering feels loose, more than normal Jeep sloppiness.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Steering & Suspension',
    customer_name: 'Ben C.',
    vehicle: { year: 2014, make: 'Jeep', model: 'Wrangler' },
    created_at: ago(3, 3),
    updated_at: ago(3, 3),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: {
      intake_id: 'demo-08',
      on_target: 'yes',
      repair_performed: 'Replaced both tie rod ends and drag link',
      accuracy_score: 82,
      comment: 'spot on, tie rods + drag link',
      created_at: ago(2, 22),
      rated_by: 'demo-owner-0000',
    },
  },
  {
    id: 'demo-09',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Transmission',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'TCM software needs relearn/update', confidence: 61 },
        { cause: 'Shift solenoid pack wear', confidence: 44 },
      ],
      componentsToInspect: ['TCM software version', 'Shift solenoid pack', 'Transmission fluid condition'],
      estimateRange: [150, 650],
      symptomLanguage: [
        'Hard clunk shifting from 2nd to 3rd, especially cold.',
        'Dealer said it might need a software update.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Transmission',
    customer_name: 'Renee F.',
    vehicle: { year: 2019, make: 'Chevrolet', model: 'Silverado' },
    created_at: ago(3, 6),
    updated_at: ago(3, 6),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: {
      intake_id: 'demo-09',
      on_target: 'partially',
      repair_performed: 'Solenoid pack replaced',
      accuracy_score: 55,
      comment:
        "Software update alone didn't fix it — ended up replacing the solenoid pack. Partial credit, right system, wrong part.",
      created_at: ago(2, 20),
      rated_by: 'demo-tech-0001',
    },
  },
  {
    id: 'demo-10',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Body & Trim',
      urgency: 'monitor',
      urgencyLabel: 'Schedule within a couple weeks',
      probableCauses: [
        { cause: 'Loose rear trunk liner clip', confidence: 52 },
        { cause: 'Rear left suspension link bushing play', confidence: 37 },
      ],
      componentsToInspect: [
        'Trunk liner clips and trim',
        'Rear left lower control arm bushings',
        'Rear subframe mounts',
      ],
      estimateRange: [0, 180],
      symptomLanguage: [
        'Rattle from the back left only over rough pavement, not on smooth highway.',
        "Doesn't happen at low speed, only bumps.",
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: true, video: false, text: true },
    },
    urgency: 'monitor',
    category: 'Body & Trim',
    customer_name: 'Alicia N.',
    vehicle: { year: 2022, make: 'Tesla', model: 'Model 3' },
    created_at: ago(3, 1),
    updated_at: ago(3, 1),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },

  // Last week
  {
    id: 'demo-11',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Belts & Accessory Drive',
      urgency: 'routine',
      urgencyLabel: 'Routine — schedule when convenient',
      probableCauses: [
        { cause: 'Glazed/worn serpentine belt', confidence: 74 },
        { cause: 'Slack accessory belt tensioner', confidence: 30 },
      ],
      componentsToInspect: ['Serpentine belt condition', 'Belt tensioner pulley'],
      estimateRange: [40, 160],
      symptomLanguage: [
        "Loud squeal for the first 10 seconds after starting, especially when it's cold out.",
        'Goes away once the car warms up.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'routine',
    category: 'Belts & Accessory Drive',
    customer_name: 'Oscar M.',
    vehicle: { year: 2013, make: 'Honda', model: 'Accord' },
    created_at: ago(6, 4),
    updated_at: ago(6, 4),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: {
      intake_id: 'demo-11',
      on_target: 'yes',
      repair_performed: 'Replaced serpentine belt and tensioner',
      accuracy_score: 88,
      comment: 'Exactly right, belt was glazed.',
      created_at: ago(5, 22),
      rated_by: 'demo-tech-0002',
    },
  },
  {
    id: 'demo-12',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Brakes',
      urgency: 'immediate',
      urgencyLabel: 'See us today',
      probableCauses: [
        { cause: 'Stuck brake caliper causing overheating', confidence: 66 },
        { cause: 'Emergency brake left partially engaged', confidence: 22 },
      ],
      componentsToInspect: ['Front and rear calipers', 'Parking brake engagement', 'Brake fluid condition'],
      estimateRange: [150, 420],
      symptomLanguage: [
        'Burning smell after driving on the highway for a while.',
        'Smells kind of like hot rubber or oil.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: false, photo: false, video: false, text: true },
    },
    urgency: 'immediate',
    category: 'Brakes',
    customer_name: 'Deja W.',
    vehicle: { year: 2018, make: 'Hyundai', model: 'Sonata' },
    created_at: ago(6, 8),
    updated_at: ago(6, 8),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: {
      intake_id: 'demo-12',
      on_target: 'no',
      repair_performed: 'Replaced leaking valve cover gasket — oil was dripping onto the exhaust manifold',
      accuracy_score: 20,
      comment: 'Not brakes at all — valve cover gasket was leaking oil onto the exhaust. Good instinct on urgency at least.',
      created_at: ago(5, 20),
      rated_by: 'demo-owner-0000',
    },
  },
  {
    id: 'demo-13',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Engine',
      urgency: 'immediate',
      urgencyLabel: 'See us today',
      probableCauses: [
        { cause: 'Failing ignition coil on cylinder 3', confidence: 69 },
        { cause: 'Fouled spark plug', confidence: 41 },
      ],
      componentsToInspect: ['Ignition coils', 'Spark plugs', 'Fuel injectors'],
      estimateRange: [90, 320],
      symptomLanguage: [
        'Car shakes at idle and check engine light is flashing.',
        'Started yesterday, got worse overnight.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: true, photo: false, video: false, text: true },
    },
    urgency: 'immediate',
    category: 'Engine',
    customer_name: 'Frank D.',
    vehicle: { year: 2011, make: 'Kia', model: 'Optima' },
    created_at: ago(7, 2),
    updated_at: ago(6, 20),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: ago(6, 20),
    rating: null,
  },
  {
    id: 'demo-14',
    shop_id: demoShop.id,
    status: 'complete',
    brief: {
      type: 'final',
      category: 'Tires & Wheels',
      urgency: 'routine',
      urgencyLabel: 'Routine — schedule when convenient',
      probableCauses: [
        { cause: 'Seasonal tire pressure drop', confidence: 70 },
        { cause: 'Slow leak from a small puncture', confidence: 35 },
      ],
      componentsToInspect: ['Tire pressure all four corners', 'Visual inspection for punctures', 'TPMS sensor battery'],
      estimateRange: [0, 40],
      symptomLanguage: [
        'TPMS light came on this week, temperature dropped a lot.',
        'No visible flat tire, all look normal.',
      ],
      disclaimer: DISCLAIMER,
      inputs: { audio: false, photo: false, video: false, text: true },
    },
    urgency: 'routine',
    category: 'Tires & Wheels',
    customer_name: 'Lauren P.',
    vehicle: { year: 2020, make: 'Mazda', model: 'CX-5' },
    created_at: ago(6, 12),
    updated_at: ago(6, 12),
    flagged: false,
    flagged_reason: null,
    flagged_at: null,
    archived_at: null,
    rating: null,
  },
]

export const demoBundles = {
  'demo-01': {
    messages: [
      { id: 'demo-01-m1', role: 'interviewer', content: 'Tell me about the sound — when do you hear it?', created_at: ago(0, 3) },
      {
        id: 'demo-01-m2',
        role: 'user',
        content: "It sounds like a hairdryer when I brake going downhill on 250, but only if the car's been sitting a while.",
        created_at: ago(0, 3),
      },
      { id: 'demo-01-m3', role: 'interviewer', content: 'Does it get better or worse the longer you drive?', created_at: ago(0, 3) },
      { id: 'demo-01-m4', role: 'user', content: 'Gets quieter after a few stops.', created_at: ago(0, 3) },
      { id: 'demo-01-m5', role: 'interviewer', content: 'Any pulsation or grinding feeling through the pedal?', created_at: ago(0, 3) },
      { id: 'demo-01-m6', role: 'user', content: 'No grinding, just the squeal. Pedal feels normal.', created_at: ago(0, 3) },
      {
        id: 'demo-01-m7',
        role: 'interviewer',
        content: 'Got it. Can you upload a photo of the front wheel and a quick recording of the sound?',
        created_at: ago(0, 3),
      },
      { id: 'demo-01-m8', role: 'user', content: 'Attached a photo and a quick audio clip of the sound.', created_at: ago(0, 3) },
    ],
    media: [
      {
        id: 'demo-01-media-1',
        intake_id: 'demo-01',
        kind: 'photo',
        text_content: null,
        storage_path: null,
        mime_type: 'image/jpeg',
        duration_seconds: null,
        signed_url: photo('Demo Photo — Front Wheel'),
        created_at: ago(0, 3),
      },
      {
        id: 'demo-01-media-2',
        intake_id: 'demo-01',
        kind: 'audio',
        text_content: null,
        storage_path: null,
        mime_type: 'audio/wav',
        duration_seconds: 8,
        signed_url: SILENT_AUDIO_DATA_URI,
        created_at: ago(0, 3),
      },
    ],
  },
  'demo-04': {
    messages: [
      { id: 'demo-04-m1', role: 'interviewer', content: "What's going on with your F-150 today?", created_at: ago(1, 4) },
      { id: 'demo-04-m2', role: 'user', content: 'Nothing wrong with driving, just want to show you the seats.', created_at: ago(1, 4) },
      {
        id: 'demo-04-m3',
        role: 'interviewer',
        content:
          'This intake is for vehicle mechanical issues — is there a noise, warning light, or performance problem you want us to look at?',
        created_at: ago(1, 4),
      },
      { id: 'demo-04-m4', role: 'user', content: "No, just the interior wear, see the photos I'm sending.", created_at: ago(1, 4) },
      {
        id: 'demo-04-m5',
        role: 'interviewer',
        content: "I've noted that. If you have a mechanical concern in the future, feel free to start a new intake.",
        created_at: ago(1, 3),
      },
    ],
    media: [1, 2, 3, 4, 5, 6].map((n) => ({
      id: `demo-04-media-${n}`,
      intake_id: 'demo-04',
      kind: 'photo',
      text_content: null,
      storage_path: null,
      mime_type: 'image/jpeg',
      duration_seconds: null,
      signed_url: photo(`Demo Photo — Interior ${n}`),
      created_at: ago(1, 4),
    })),
  },
  'demo-10': {
    messages: [
      { id: 'demo-10-m1', role: 'interviewer', content: 'Where do you hear the rattle coming from?', created_at: ago(3, 1) },
      {
        id: 'demo-10-m2',
        role: 'user',
        content: 'Rattle from the back left only over rough pavement, not on smooth highway.',
        created_at: ago(3, 1),
      },
      { id: 'demo-10-m3', role: 'interviewer', content: 'Does it happen at low speeds too, like pulling into a driveway?', created_at: ago(3, 1) },
      { id: 'demo-10-m4', role: 'user', content: "Doesn't happen at low speed, only bumps.", created_at: ago(3, 1) },
      {
        id: 'demo-10-m5',
        role: 'interviewer',
        content: 'Is there anything loose in the trunk or cargo area that could be shifting?',
        created_at: ago(3, 1),
      },
      { id: 'demo-10-m6', role: 'user', content: 'Trunk is empty, nothing loose that I can see.', created_at: ago(3, 1) },
      {
        id: 'demo-10-m7',
        role: 'interviewer',
        content: "Thanks — I'll flag the trunk liner clips and rear suspension bushings for the tech to check.",
        created_at: ago(3, 1),
      },
    ],
    media: [
      {
        id: 'demo-10-media-1',
        intake_id: 'demo-10',
        kind: 'photo',
        text_content: null,
        storage_path: null,
        mime_type: 'image/jpeg',
        duration_seconds: null,
        signed_url: photo('Demo Photo — Rear Left Trunk'),
        created_at: ago(3, 1),
      },
      {
        id: 'demo-10-media-2',
        intake_id: 'demo-10',
        kind: 'audio',
        text_content: null,
        storage_path: null,
        mime_type: 'audio/wav',
        duration_seconds: 6,
        signed_url: SILENT_AUDIO_DATA_URI,
        created_at: ago(3, 1),
      },
    ],
  },
}

export const DEMO_BRIEF_INTAKE_ID = 'demo-10'
