-- Greenlit v2 initial schema
-- Tables: shops, shop_members, intakes, intake_messages, intake_media,
--         intake_ratings, llm_call_log
-- Do not edit this file after landing — use 0002_*.sql for changes.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE shops (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug       text UNIQUE NOT NULL,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shop_members (
  shop_id uuid NOT NULL REFERENCES shops (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  role    text NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'member')),
  PRIMARY KEY (shop_id, user_id)
);

CREATE TABLE intakes (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shop_id       uuid REFERENCES shops (id) ON DELETE SET NULL,
  status        text NOT NULL DEFAULT 'in_progress'
                CHECK (status IN ('in_progress', 'complete')),
  brief         jsonb,
  urgency       text CHECK (urgency IS NULL OR urgency IN ('immediate', 'monitor', 'routine')),
  category      text,
  customer_name text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE intake_messages (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id  uuid NOT NULL REFERENCES intakes (id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('user', 'interviewer', 'diagnostician', 'system')),
  content    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX intake_messages_intake_id_created_at_idx
  ON intake_messages (intake_id, created_at);

CREATE TABLE intake_media (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id        uuid NOT NULL REFERENCES intakes (id) ON DELETE CASCADE,
  kind             text NOT NULL CHECK (kind IN ('audio', 'video', 'photo', 'text')),
  storage_path     text,
  text_content     text,
  mime_type        text,
  duration_seconds numeric,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT intake_media_storage_or_text CHECK (
    (kind = 'text' AND text_content IS NOT NULL AND storage_path IS NULL)
    OR (kind <> 'text' AND storage_path IS NOT NULL)
  )
);

CREATE INDEX intake_media_intake_id_idx ON intake_media (intake_id);

CREATE TABLE intake_ratings (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id        uuid NOT NULL UNIQUE REFERENCES intakes (id) ON DELETE CASCADE,
  rated_by         uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  on_target        text NOT NULL CHECK (on_target IN ('yes', 'partially', 'no')),
  repair_performed text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE llm_call_log (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id  uuid NOT NULL REFERENCES intakes (id) ON DELETE CASCADE,
  called_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX llm_call_log_intake_id_called_at_idx
  ON llm_call_log (intake_id, called_at);

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER intakes_set_updated_at
  BEFORE UPDATE ON intakes
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION is_shop_member(p_shop_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM shop_members sm
    WHERE sm.shop_id = p_shop_id
      AND sm.user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION intake_created_within_30_minutes(p_intake_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM intakes i
    WHERE i.id = p_intake_id
      AND i.created_at > now() - interval '30 minutes'
  );
$$;

CREATE OR REPLACE FUNCTION shop_id_for_intake(p_intake_id uuid)
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT i.shop_id FROM intakes i WHERE i.id = p_intake_id;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE shop_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE intakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE intake_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE intake_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE intake_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE llm_call_log ENABLE ROW LEVEL SECURITY;

-- shops: anon SELECT (shop name on QR page). No public writes.
CREATE POLICY shops_anon_select
  ON shops FOR SELECT
  TO anon
  USING (true);

CREATE POLICY shops_authenticated_select
  ON shops FOR SELECT
  TO authenticated
  USING (true);

-- shop_members: only same-shop members SELECT.
CREATE POLICY shop_members_select_same_shop
  ON shop_members FOR SELECT
  TO authenticated
  USING (
    shop_id IN (
      SELECT sm.shop_id FROM shop_members sm WHERE sm.user_id = auth.uid()
    )
  );

-- intakes: anon INSERT only. No anon SELECT.
CREATE POLICY intakes_anon_insert
  ON intakes FOR INSERT
  TO anon
  WITH CHECK (
    status = 'in_progress'
    AND brief IS NULL
    AND urgency IS NULL
    AND category IS NULL
  );

CREATE POLICY intakes_shop_member_select
  ON intakes FOR SELECT
  TO authenticated
  USING (shop_id IS NOT NULL AND is_shop_member(shop_id));

CREATE POLICY intakes_shop_member_update
  ON intakes FOR UPDATE
  TO authenticated
  USING (shop_id IS NOT NULL AND is_shop_member(shop_id))
  WITH CHECK (shop_id IS NOT NULL AND is_shop_member(shop_id));

-- intake_messages: anon INSERT within 30-min window. Shop members SELECT.
CREATE POLICY intake_messages_anon_insert
  ON intake_messages FOR INSERT
  TO anon
  WITH CHECK (intake_created_within_30_minutes(intake_id));

CREATE POLICY intake_messages_shop_member_select
  ON intake_messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  );

-- intake_media: anon INSERT within 30-min window. Shop members SELECT.
CREATE POLICY intake_media_anon_insert
  ON intake_media FOR INSERT
  TO anon
  WITH CHECK (intake_created_within_30_minutes(intake_id));

CREATE POLICY intake_media_shop_member_select
  ON intake_media FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  );

-- intake_ratings: authed shop members only.
CREATE POLICY intake_ratings_shop_member_select
  ON intake_ratings FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  );

CREATE POLICY intake_ratings_shop_member_insert
  ON intake_ratings FOR INSERT
  TO authenticated
  WITH CHECK (
    rated_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  );

CREATE POLICY intake_ratings_shop_member_update
  ON intake_ratings FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  )
  WITH CHECK (
    rated_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM intakes i
      WHERE i.id = intake_id
        AND i.shop_id IS NOT NULL
        AND is_shop_member(i.shop_id)
    )
  );

-- llm_call_log: no client policies — Edge Function uses service_role only.

-- ---------------------------------------------------------------------------
-- Storage: private intake-media bucket
-- ---------------------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'intake-media',
  'intake-media',
  false,
  52428800, -- 50 MiB
  ARRAY[
    'audio/webm', 'audio/mp4', 'audio/mpeg', 'audio/wav', 'audio/ogg',
    'video/webm', 'video/mp4', 'video/quicktime',
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Anon INSERT only under {intake_id}/ prefix during 30-min window.
CREATE POLICY intake_media_storage_anon_insert
  ON storage.objects FOR INSERT
  TO anon
  WITH CHECK (
    bucket_id = 'intake-media'
    AND (storage.foldername(name))[1] IS NOT NULL
    AND intake_created_within_30_minutes(((storage.foldername(name))[1])::uuid)
  );

-- Shop members may read objects for intakes belonging to their shop.
CREATE POLICY intake_media_storage_shop_member_select
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'intake-media'
    AND (storage.foldername(name))[1] IS NOT NULL
    AND is_shop_member(shop_id_for_intake(((storage.foldername(name))[1])::uuid))
  );

-- ---------------------------------------------------------------------------
-- Seed: demo shop
-- ---------------------------------------------------------------------------

INSERT INTO shops (slug, name)
VALUES ('demo-shop', 'Demo Shop')
ON CONFLICT (slug) DO NOTHING;

-- TODO: replace with production demo email
INSERT INTO shop_members (shop_id, user_id, role)
SELECT s.id, u.id, 'owner'
FROM shops s
CROSS JOIN auth.users u
WHERE s.slug = 'demo-shop'
  AND u.email = 'yashbolishetti@gmail.com'
ON CONFLICT DO NOTHING;
